port = 3001
storage_path = "default.db"
gateway_endpoint = "http://127.0.0.1"

[consul_config]
consul_addr = "http://127.0.0.1:8500"
node = "Local"
service_name = "req_cache"
service_address = "127.0.0.1"
service_port = 3001

[log_config]
max_level = "info"
filter = "info"
# max_level = "debug"
# filter = "debug,hyper=info,opendal=info,sled=info"
# rolling_file_path = "./logs"
service_name = "req_cache"
# agent_endpoint = "127.0.0.1:6831"
