[req_cache]
port = 3001

[req_cache.consul_config]
consul_addr = "http://127.0.0.1:8500"
node = "Local"
service_name = "req_cache"
service_address = "192.168.12.31"
service_port = 3001

[req_cache.log_config]
max_level = "debug"
filter = "debug,hyper=info"
# rolling_file_path = "./logs"
service_name = "req_cache"
# agent_endpoint = "127.0.0.1:6831"
